name: Respond to Event

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Event received
        run: echo "Event received"
