name: Repository Dispatch

on:
  repository_dispatch:
    types: [push]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - name: Event received
        run: echo "Event received"
